#pragma once

	class BlendEffect : public Effect
	{
		enum class BlendMode
		{
			BLEND_MODE_DARKEN,
			BLEND_MODE_MULTIPLY,
			BLEND_MODE_COLOR_BURN,
			BLEND_MODE_LINEAR_BURN,
			BLEND_MODE_DARKER_COLOR,
			BLEND_MODE_LIGHTEN,
			BLEND_MODE_SCREEN,
			BLEND_MODE_COLOR_DODGE,
			BLEND_MODE_LINEAR_DODGE,
			BLEND_MODE_LIGHTER_COLOR,
			BLEND_MODE_OVERLAY,
			BLEND_MODE_SOFT_LIGHT,
			BLEND_MODE_HARD_LIGHT,
			BLEND_MODE_VIVID_LIGHT,
			BLEND_MODE_LINEAR_LIGHT,
			BLEND_MODE_PIN_LIGHT,
			BLEND_MODE_HARD_MIX,
			BLEND_MODE_DIFFERENCE,
			BLEND_MODE_EXCLUSION,
			BLEND_MODE_HUE,
			BLEND_MODE_SATURATION,
			BLEND_MODE_COLOR,
			BLEND_MODE_LUMINOSITY,
			BLEND_MODE_DISSOLVE,
			BLEND_MODE_SUBTRACT,
			BLEND_MODE_DIVISION
		};
	public:
		std::wstring* other;
		BlendMode blendMode;
	public:
		BlendEffect();
		void SetBlendMode(BlendMode);
		void SetOtherImage(std::wstring);
	};
